blank_issues_enabled: false # ë¹ˆ ì´ìŠˆ ì˜µì…˜ ìˆ¨ê¸°ê¸°

issue_templates:
    - name: "ğŸ”¨ WBS ê¸°ë°˜ ê¸°ëŠ¥ ì´ìŠˆ"
      about: "WBS í•­ëª©ì— ë”°ë¼ ë°±ì—”ë“œ/í”„ë¡ íŠ¸ì—”ë“œ ê¸°ëŠ¥ ì´ìŠˆë¥¼ ìƒì„±í•©ë‹ˆë‹¤"
      title: "[{{component}}-{{feature_code}}] {{feature_name}}"
      labels: []
      assignees: []
      template: "wbs_feature.yml"
