blank_issues_enabled: true

issue_templates:
  - name: "ğŸ”¨ WBS ë°±ì—”ë“œ ê¸°ëŠ¥ ì´ìŠˆ"
    about: "Allready í”„ë¡œì íŠ¸ WBSì˜ ë°±ì—”ë“œ í•­ëª©ì— ë”°ë¼ ê¸°ëŠ¥ ì´ìŠˆë¥¼ ìƒì„±í•©ë‹ˆë‹¤"
    title: "BE-${{ inputs.wbs_code }}-${{ inputs.feature_name }}"
    assignees: []
    template: "backend_wbs_feature.yml"

  - name: "ğŸŒ WBS í”„ë¡ íŠ¸ì—”ë“œ ê¸°ëŠ¥ ì´ìŠˆ"
    about: "Allready í”„ë¡œì íŠ¸ WBSì˜ í”„ë¡ íŠ¸ì—”ë“œ í•­ëª©ì— ë”°ë¼ ê¸°ëŠ¥ ì´ìŠˆë¥¼ ìƒì„±í•©ë‹ˆë‹¤"
    title: "FE-${{ inputs.wbs_code }}-${{ inputs.feature_name }}"
    assignees: []
    template: "frontend_wbs_feature.yml"
